### ISSUE TITLE
please add concurrency folder for v0.12.1 tag 

### ISSUE THREAD

**Issue by halokid** [dapr/kit#76]
## Describe the proposal
when install depend for dapr,  found this error 
```
go: module github.com/dapr/kit@upgrade found (v0.12.1), but does not contain package github.com/dapr/kit/concurrency
```
check `v0.12.1` found this tag no consist the `concurrency` folder,  so please add this folder with no compatibility issue and push to `v0.12.1` fix this problem,  thanks.

**Comment by ItalyPaleAle** [comment]
This is now in 0.13.0

By the way, you can always get a version from a git branch, for example:

```
go get -u github.com/dapr/kit@main
```

PS: Although dapr/kit _can_ be used outside of Dapr, it's not something officially supported. Most importantly, the APIs are not stable and we often make breaking changes :)
